project:
  type: website
  output-dir: docs
  resources:
    - "CNAME"
    - "robots.txt"
    - ".nojekyll"

website:
  title: "Pristine Seas Science Team SOP"
  favicon: "assets/logos/PSHorizontalColor.png"
  site-url: "https://sop.pristine-seas.org"
  repo-url: "https://github.com/pristine-seas/sop"
  repo-actions: [edit, issue]
  
  navbar:
    background: primary
    search: true
    pinned: true
    logo: "assets/logos/PSHorizontalColor.png"
    title: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "Collaborative Infrastructure"
        href: collaborative-infra/index.qmd
      - text: "Field Methods"
        href: field-methods/index.qmd
        menu:
          - text: "Overview"
            href: field-methods/index.qmd
          - text: "Underwater Visual Surveys"
            href: field-methods/uvs_overview.qmd
          - text: "Benthic Surveys"
            href: field-methods/benthic_overview.qmd
            menu:
              - text: "LPI"
                href: field-methods/benthic_lpi.qmd
              - text: "Inverts"
                href: field-methods/benthic_inverts.qmd
              - text: "Recruits"
                href: field-methods/benthic_recuirts.qmd 
          - text: "Fish Surveys"
            href: field-methods/fish-surveys.qmd
          - text: "eDNA"
            href: field-methods/edna.qmd
          - text: "Seabed BRUVS"
            href: field-methods/seabed-bruvs.qmd
          - text: "Pelagic BRUVS"
            href: field-methods/pelagic-bruvs.qmd
          - text: "Seabird & Mammals"
            href: field-methods/seabird-mammals.qmd
          - text: "ROV Surveys"
            href: field-methods/rov-surveys.qmd
          - text: "Submersible Surveys"
            href: field-methods/submersible.qmd
          - text: "Deep Sea Cameras"
            href: field-methods/drop-cameras.qmd
      - text: "Expedition Planning"
        href: expedition-planning/index.qmd
      - text: "Media Library"
        href: media-library/index.qmd
      - text: "Other Resources"
        href: other/index.qmd
    
    right:
      - icon: github
        href: https://github.com/pristine-seas/sop
      - icon: globe
        href: https://pristine-seas.org
  
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Collaborative Infrastructure"
        contents:
          - collaborative-infra/index.qmd
          - collaborative-infra/drive.qmd
          - collaborative-infra/github.qmd
          - collaborative-infra/bigquery.qmd
          - collaborative-infra/zotero.qmd
          - collaborative-infra/argo_NAS.qmd
      - section: "Field Methods"
        contents:
          - field-methods/index.qmd
          - text: "Underwater Visual Surveys (UVS)"
            contents:
              - field-methods/uvs_overview.qmd
              - text: "Benthos"
                contents:
                  - field-methods/benthic_overview.qmd
                  - field-methods/benthic_lpi.qmd
                  - field-methods/benthic_inverts.qmd
                  - field-methods/benthic_recruits.qmd
              - text: "Fish"
                contents:
                  - field-methods/fish-surveys.qmd
          - text: "BRUVS Surveys"
            contents:
              - text: "Seabed"
                href: field-methods/seabed-bruvs.qmd
              - text: "Pelagic"
                href: field-methods/pelagic-bruvs.qmd
          - text: "Deep-Sea"
            contents:
              - field-methods/rov-surveys.qmd
              - field-methods/submersible.qmd
              - field-methods/drop-cameras.qmd
          - field-methods/seabird-mammals.qmd
      - section: "Expedition Planning"
        contents:
          - expedition-planning/index.qmd
          - expedition-planning/science-lead.qmd
          - expedition-planning/communities.qmd
          - expedition-planning/site-selection.qmd
          - expedition-planning/permits-mou.qmd
      - section: "Media Library"
        contents:
          - media-library/index.qmd
          - media-library/collection.qmd
          - media-library/organization.qmd
          - media-library/metadata.qmd
      - section: "Appendices"
        contents:
          - appendices/index.qmd
          - appendices/species-guides.qmd
          - appendices/manuals.qmd
          - appendices/partners.qmd
  
  page-footer:
    left: "© 2025 Pristine Seas"
    right:
      - icon: github
        href: https://github.com/pristine-seas/sop
      - icon: globe
        href: https://pristine-seas.org

format:
  html:
    theme: cosmo
    css: assets/css/pristine_seas.css
    toc: true
    toc-depth: 3
    toc-location: right
    code-fold: true
    code-tools: true
    highlight-style: github
    anchor-sections: true
    fig-cap-location: bottom
    link-external-icon: true
    link-external-newwindow: true

execute:
  freeze: auto
  echo: true
  warning: false
  message: false
  